バグ対応
tricore-r-hattori/BreakingTiles pull request #13
Opened 2021-08-06 05:35 UTC by tricore-r-hattori

手が瓦に埋まる問題とゲーム中に瓦をクリックすると手が瞬間移動する問題を解決しました。

確認点
〇Script
・PositionSynchronize
・ScrollControllObjectHitCheck
〇Prefab
・GamePlayRoot
・TutorialRoot
・Hand

確認方法
・GameSceneが起動シーン。
・ゲーム中に手が画面左右から出ないことを確認。
・ゲーム中に瓦をクリックしても手が瞬間移動しないことを確認。

2021-08-06 05:50 UTC, tricore-as05 requested changes

2021-08-06 05:50 UTC, tricore-as05 commented on Assets/Script/Hand/PositionSynchronize.cs
> +    void LeftFixHand()
[MUST]
移動制限がすごく汚いです
Mathf.Clampとかで何とかなると思うので調べてください

2021-08-06 06:08 UTC, tricore-r-hattori commented on Assets/Script/Hand/PositionSynchronize.cs
> +    void LeftFixHand()
Mathf.Clampを使用した設計に修正しました。

2021-08-06 06:13 UTC, tricore-as05 requested changes

2021-08-06 06:13 UTC, tricore-as05 commented on Assets/Script/Hand/PositionSynchronize.cs
> +        gameObject.transform.position = fixHandPosition;
[MUST]
今の実装方法だとfixHandPositionいらないと思います
gameObject.transform.positionに直でいれてしまってもいいはずです。

2021-08-06 06:18 UTC, tricore-r-hattori commented on Assets/Script/Hand/PositionSynchronize.cs
> +        gameObject.transform.position = fixHandPosition;
Mathf.Clampの計算をgameObject.transform.positionに直接いれて修正しました。

2021-08-06 06:22 UTC, tricore-as05 reviewed
一気に気づけなくて申し訳ないんですが、
Qが1件あるので確認をお願いします。

2021-08-06 06:22 UTC, tricore-as05 commented on Assets/Script/Hand/PositionSynchronize.cs
> +    RaycastHit2D hitObject = default;
[Q]
hitObject をローカルに持つ理由ってありますか？
CheckMouseHitObjectの先頭に定義するだけでいい気がしますが

2021-08-06 06:31 UTC, tricore-r-hattori commented on Assets/Script/Hand/PositionSynchronize.cs
> +    RaycastHit2D hitObject = default;
CheckMouseHitObject()はUpdate()で呼んでいるのでhitObjectを毎フレーム定義することになり、コストがかかると思ったのでhitObjectをローカルで持つようにしました。

・ローカルで定義する
・CheckMouseHitObject()のスコープ内で定義する(ただし毎フレーム呼ばれる)

どちらの方が処理的にコストがかからないのでしょうか？

2021-08-10 05:20 UTC, tricore-r-hattori commented on Assets/Script/Hand/PositionSynchronize.cs
> +    RaycastHit2D hitObject = default;
hitObjectをCheckMouseHitObjectの先頭に定義してしまうとクリックしたその1フレームしか手の座標が動かなくなります。
それを解決するために、hitObjectをローカルに保存しておき、クリックしているときに手の座標が常に動くようにしました。
なので、hitObject をローカルに定義しています。

2021-08-10 05:22 UTC, tricore-as05 approved these changes
LGTM

2021-08-10 05:51 UTC, tricore-t-yui approved these changes
lgtm
nits1件

2021-08-10 05:51 UTC, tricore-t-yui commented on Assets/Script/Hand/PositionSynchronize.cs
> +        fixHandWorldSize = fixHandPoint.transform.TransformPoint(fixHandPoint.rect.size / HalfSize);
[nits]
流石に半分にするくらいの処理ならconstじゃなくていい
あと割り算はコスト高いので普通は*0.5fで対応する

2021-08-10 06:05 UTC, tricore-r-hattori commented on Assets/Script/Hand/PositionSynchronize.cs
> +        fixHandWorldSize = fixHandPoint.transform.TransformPoint(fixHandPoint.rect.size / HalfSize);
HalfSizeを * 0.5fに変更しました。

2021-08-10 06:05 UTC, merged