スワイプ時の力の計算
tricore-r-hattori/BreakingTiles pull request #3
Opened 2021-07-19 08:59 UTC by tricore-r-hattori

スワイプ時の力の計算を実装しました。

確認点
〇Script
・HandSwipeForceCalculation
・PositionSynchronizeObject
〇Prefab
・Hand
・Tile

2021-07-19 09:15 UTC, tricore-as05 requested changes

2021-07-19 09:15 UTC, tricore-as05 commented on Assets/Script/HandSwipeForceCalculation.cs
> +
[MUST]
クラスコメント

2021-07-19 09:15 UTC, tricore-as05 commented on Assets/Script/HandSwipeForceCalculation.cs
> +            distance = Mathf.Abs(Vector3.Distance(handPos, tilePos));
[Q]
距離を取っているのはわかるのですが、どこで速度計算をやってますか？

2021-07-19 09:15 UTC, tricore-as05 commented on Assets/Script/HandSwipeForceCalculation.cs
> +        tilePos.y += correctionTilePositionsY;
[MUST]
スワイプ時の力の計算というタスクなので、瓦の位置設定が仮なのはわかるのですが、
せめてコメントで残しておいてください
仮の変数、処理も全部わかるようにお願いします。

2021-07-19 09:15 UTC, tricore-as05 commented on Assets/Script/HandSwipeForceCalculation.cs
> +        if (frameCount % 60.0f == 0)
[MUST]
60.0fというマジックナンバーではなく、getPositionTimeが定義されてあるので使ってください
また、この秒数は1秒で固定ですか？
調整する必要があるのなら、constではなく[SerializeField]でいつでも変更できるようにした方が良いかと思います。

2021-07-19 09:15 UTC, tricore-as05 commented on Assets/Script/HandSwipeForceCalculation.cs
> +    // 瓦との当たり判定をとっていないので瓦を割るタスクを行う際にここの処理を書きます。
[MUST]
見るからにTODOコメントなので、下記のような記述にしてください
`// TODO: 瓦との当たり判定をとっていないので瓦を割るタスクを行う際にここの処理を書きます。`

2021-07-19 09:15 UTC, tricore-as05 commented on Assets/Script/HandSwipeForceCalculation.cs
> +        // 瓦との当たり判定を取っていないので、ここの条件式は一旦仮でマウスの左ボタンを離した時に処理を行うようにしています。
[MUST]
こういった説明文はNOTEコメントにしてください
```
// NOTE: 瓦との当たり判定を取っていないので、ここの条件式は一旦仮でマウスの左ボタンを離した時に処理を行うようにしています。
//       本来は瓦と当たった時のフラグを条件式にします。
```

2021-07-19 09:15 UTC, tricore-as05 commented on Assets/Script/PositionSynchronizeObject.cs
> +	}
[nits]
改行時の行間がかなり広くなっているため、修正できるようでしたら修正してください

2021-07-19 09:15 UTC, tricore-as03 requested changes

2021-07-19 09:15 UTC, tricore-as03 commented on Assets/Script/HandSwipeForceCalculation.cs
> +public class HandSwipeForceCalculation : MonoBehaviour
[MUST]
クラスコメント書いてください。

2021-07-19 09:15 UTC, tricore-as03 commented on Assets/Script/HandSwipeForceCalculation.cs
> +    Vector3 handPos = new Vector3(0.0f,0.0f,0.0f);
[nits]
Vector3.zeroというプロパティがあるので、それを使うのもありです。

2021-07-19 09:15 UTC, tricore-as03 commented on Assets/Script/HandSwipeForceCalculation.cs
> +            distance = Mathf.Abs(Vector3.Distance(handPos, tilePos));
[MUST]
Vector3.Distanceはルートの計算のせいで負荷が高いので、Vector3.sqrMagnitudeを使うと良いです。
ただ、Vector3.sqrMagnitudeは距離を二乗した値が返ってくるので、その値を使用して別の計算を行う場合は、計算式のもう片方の値も２乗してあげる必要があります。
https://www.stmn.tech/entry/2016/06/15/033835

2021-07-19 09:15 UTC, tricore-as03 commented on Assets/Script/PositionSynchronizeObject.cs
> +				mouseScreenPosition.z = 10f;
[MUST]
コードに直接値を書くのではなく定数を用意してください。

2021-07-19 09:16 UTC, tricore-as05 requested changes

2021-07-19 09:16 UTC, tricore-as05 commented on Assets/Script/HandSwipeForceCalculation.cs
> +    float speed = 0.0f;
[MUST]
speed(速度)なのか、swipeForce(スワイプ時の力)なのか表記ブレしているので、どちらかに統一してください

2021-07-19 09:29 UTC, tricore-r-hattori commented on Assets/Script/HandSwipeForceCalculation.cs
> +
コメントを書いて修正しました。

2021-07-19 09:30 UTC, tricore-r-hattori commented on Assets/Script/HandSwipeForceCalculation.cs
> +        tilePos.y += correctionTilePositionsY;
コメントを書いて修正しました。

2021-07-19 09:32 UTC, tricore-r-hattori commented on Assets/Script/HandSwipeForceCalculation.cs
> +        if (frameCount % 60.0f == 0)
getPositionTimeを使用し、[SerializeField]でいつでも変更できるようにしました。

2021-07-19 09:32 UTC, tricore-r-hattori commented on Assets/Script/HandSwipeForceCalculation.cs
> +    // 瓦との当たり判定をとっていないので瓦を割るタスクを行う際にここの処理を書きます。
TODOコメントに変更しました。

2021-07-19 09:32 UTC, tricore-r-hattori commented on Assets/Script/HandSwipeForceCalculation.cs
> +        // 瓦との当たり判定を取っていないので、ここの条件式は一旦仮でマウスの左ボタンを離した時に処理を行うようにしています。
NOTEコメントに変更しました

2021-07-19 09:33 UTC, tricore-r-hattori commented on Assets/Script/HandSwipeForceCalculation.cs
> +public class HandSwipeForceCalculation : MonoBehaviour
コメントを書いて修正しました。

2021-07-20 00:36 UTC, tricore-r-hattori commented on Assets/Script/HandSwipeForceCalculation.cs
> +    Vector3 handPos = new Vector3(0.0f,0.0f,0.0f);
Vector3.zeroで初期化して修正しました。

2021-07-20 00:59 UTC, tricore-r-hattori commented on Assets/Script/PositionSynchronizeObject.cs
> +				mouseScreenPosition.z = 10f;
correctionHandPositionsYという定数を用意して修正しました。

2021-07-20 01:35 UTC, tricore-r-hattori commented on Assets/Script/PositionSynchronizeObject.cs
> +	}
タブを使用していたのでスペース4文字に変え、行間を修正しました。

2021-07-20 01:45 UTC, tricore-r-hattori commented on Assets/Script/HandSwipeForceCalculation.cs
> +            distance = Mathf.Abs(Vector3.Distance(handPos, tilePos));
Vector3.Distance(handPos, tilePos);をVector3.SqrMagnitude(handPos - tilePos);に変え、修正しました。

2021-07-20 01:52 UTC, tricore-r-hattori commented on Assets/Script/HandSwipeForceCalculation.cs
> +            distance = Mathf.Abs(Vector3.Distance(handPos, tilePos));
スワイプする時間を1秒と固定していたので速度計算をする必要がなかったのですが、時間を[SerializeField]で値を変更できるようにしたので、下記の速度計算を行い、修正しました。

// フレームから秒の値に変換
 seconds = (getPositionTime / frameToSeconds);

 // 速度を計算
 speed = distance / seconds * seconds;

2021-07-20 02:03 UTC, tricore-r-hattori commented on Assets/Script/HandSwipeForceCalculation.cs
> +    float speed = 0.0f;
swipeForceという変数を別で用意して修正しました。
※speedは、瓦との当たり判定をとった際にスワイプ時の力の計算で使用します。

2021-07-20 02:17 UTC, tricore-as03 requested changes

2021-07-20 02:17 UTC, tricore-as03 commented on Assets/Script/HandSwipeForceCalculation.cs
> +            speed = distance / seconds * seconds;
[MUST]
「seconds * seconds」をカッコでくくったほうが良いかと。
想定だと「seconds * seconds」の計算が行われてそれをdistanceで割る、ということだとは思いますが、現状だと割り算が優先されて「distance / seconds」が先に行われてしまい結果がおかしくなると思われます。

2021-07-20 02:21 UTC, tricore-r-hattori commented on Assets/Script/HandSwipeForceCalculation.cs
> +            speed = distance / seconds * seconds;
「seconds * seconds」を()でくくり修正しました。

2021-07-20 02:25 UTC, tricore-as03 approved these changes
LGTM

2021-07-20 02:44 UTC, tricore-as05 requested changes
前回のレビューで見落としていた部分があったので、
申し訳ないですがそちらも合わせて確認をお願いします

2021-07-20 02:44 UTC, tricore-as05 commented on Assets/Script/HandSwipeForceCalculation.cs
> +        tilePos.y += correctionTilePositionsY;
[MUST]
仮のコメントとセットで、TODOコメントをお願いします

2021-07-20 02:44 UTC, tricore-as05 commented on Assets/Script/HandSwipeForceCalculation.cs
> +    const float correctionHandPositionsY = 1.3f;
[MUST]
constであれば頭文字は大文字のはずなので修正をお願いします。

また、現在constで定義されている変数はどれも調整する必要のありそうな変数なので、
constを外して[SerializeField]で調整できるようにした方がいいかと思います。

2021-07-20 02:44 UTC, tricore-as05 commented on Assets/Script/PositionSynchronizeObject.cs
> +    const float correctionHandPositionsY = 10.0f;
[MUST]
こちらも同様にconstであれば頭文字は大文字のはずなので修正をお願いします。

また、現在constで定義されている変数はどれも調整する必要のありそうな変数なので、
constを外して[SerializeField]で調整できるようにした方がいいかと思います。

2021-07-20 03:16 UTC, tricore-r-hattori commented on Assets/Script/HandSwipeForceCalculation.cs
> +    const float correctionHandPositionsY = 1.3f;
const float FrameToSeconds という変数は、フレームから秒の値に変換するために、絶対に60という数値でないといけないので定数のままにしています。それ以外は、constを外して[SerializeField]で調整できるように修正しました。

2021-07-20 03:17 UTC, tricore-r-hattori commented on Assets/Script/PositionSynchronizeObject.cs
> +    const float correctionHandPositionsY = 10.0f;
constを外して[SerializeField]で調整できるように修正しました。

2021-07-20 03:31 UTC, tricore-as05 approved these changes
LGTM

2021-07-20 03:31 UTC, merged