瓦を割っていく処理
tricore-r-hattori/BreakingTiles pull request #4
Opened 2021-07-21 08:51 UTC by tricore-r-hattori

確認点
〇Script
・HandScroll
・HandSwipeForceCalculation
・PositionSynchronize
・TileChangeImage
・TileScroll

〇Prefab
・Canvas
・hand
・Tile
・TileGroup

確認方法
・GameSceneが起動シーン
→マウスで手をクリックした状態で瓦にドラッグ
→手を瓦に当てると上から順番に割れていきます。

2021-07-21 09:11 UTC, tricore-as07 requested changes
修正が必要な箇所と質問を投げているので、
修正対応と質問の返答をお願いします。

2021-07-21 09:11 UTC, tricore-as07 commented on Assets/Script/HandScroll.cs
> +        velocity = new Vector3(0, Time.deltaTime * scrollSpeedY);
[Q]
ここでscrollSpeedYにTime.deltaTimeをかけている理由は何故でしょうか？

2021-07-21 09:11 UTC, tricore-as07 commented on Assets/Script/HandSwipeForceCalculation.cs
> +        speed = distance / (seconds * seconds);
[must]
この計算で求められているものは速度ではなく加速度だと思われます。
コメントを修正するか、計算式を修正してください。

2021-07-21 09:15 UTC, tricore-as03 requested changes

2021-07-21 09:15 UTC, tricore-as03 commented on Assets/Script/HandSwipeForceCalculation.cs
> +    public float GetSpeed { get { return speed; } }
[nits]
Ｃ＃のプロパティの機能を使えばゲッター関数を用意する必要がなくなります。
40行目のspeed変数をこのように書く。
```
public Speed { get; private set; } = 0.0f;
```
カッコ内のsetにのみprivateを付けることで「参照は外部から可能だけど、代入はクラスの中でのみ」という意味になる。
ちなみに、コーディングルールによりプロパティは定数同様パスカルケース
https://qiita.com/ShirakawaMaru/items/5f8bd065b1a4d2fdc8e0

2021-07-21 09:15 UTC, tricore-as03 commented on Assets/Script/PositionSynchronize.cs
> +    void SetObjectPos()
[MUST]
関数名がSetObjectPosなのに、中で当たったかどうかの判定と押したかどうかの判定も行っているため名前と役割があってないです。
関数名的にオブジェクトへの位置のセットしかしてはいけないので、if文の判定は呼び出し側の関数の外で行うべきかと思います。

2021-07-21 09:25 UTC, tricore-as05 requested changes

2021-07-21 09:25 UTC, tr-k-oishi commented on Assets/Script/HandScroll.cs
> +public class HandScroll : MonoBehaviour
[nits]
HandScrollerの方が良いかと

2021-07-21 09:25 UTC, tr-k-oishi commented on Assets/Script/HandScroll.cs
> +    const float ScrollEndPointY = 500.0f;
[Q]
こちらは調整する必要が無い値でしょうか？

2021-07-21 09:25 UTC, tr-k-oishi commented on Assets/Script/HandScroll.cs
> +        velocity = new Vector3(0, Time.deltaTime * scrollSpeedY);
[nits]
それぞれの処理の説明としては問題ないと思いますが、
結果的にどういった動きになるのかの説明をするようにしていただけると、
見るこっちもどういった処理をしているのかがわかりやすいです。

2021-07-21 09:25 UTC, tricore-as05 commented on Assets/Script/HandScroll.cs
> +            Destroy(gameObject);
[Q]
わざわざDestroyしている理由はなんでしょうか？
特に理由がなければSetActive(false)でよいかと。
また同シーンで再スタートとかする際に、わざわざ生成し直す必要がありそうな気がします。

2021-07-21 09:25 UTC, tricore-as05 commented on Assets/Script/PositionSynchronize.cs
> +        if (isHitPlayer)
[MUST]
if(isHitPlayer)とif (Input.GetMouseButton(0))の条件式をまとめてください

2021-07-21 09:25 UTC, tricore-as05 commented on Assets/Script/TileChangeImage.cs
> +    const float BreakTileSpriteChangePointY = -1.0f;
[MUST]
こうやってポジション系を決め打ちにするのはやめましょう、ほかの場所も同様です。

こういう場合は大体、
空のオブジェクトを用意し、そのオブジェクトのポジションとの差を見るような形になると思います。
そうすれば、空のオブジェクトの位置をいじることによって調整可能になるからです。

2021-07-21 09:25 UTC, tricore-as05 commented on Assets/Script/TileChangeImage.cs
> +public class TileChangeImage : MonoBehaviour
[MUST]
TileImageChangerかと

2021-07-21 09:25 UTC, tricore-as05 commented on Assets/Script/TileScroll.cs
> +public class TileScroll : MonoBehaviour
[MUST]
TileScrollerかと

2021-07-21 09:25 UTC, tricore-as05 commented on Assets/Script/TileScroll.cs
> +        velocity = new Vector3(0, Time.deltaTime * scrollSpeedY);
[MUST]
HandScrollと似たような処理が多いのでBaseクラスを作って一つにまとめましょう。
Baseクラスに処理を書いて、継承して使うイメージです

2021-07-21 09:26 UTC, tricore-as03 requested changes

2021-07-21 09:26 UTC, tricore-as03 commented on Assets/Script/TileScroll.cs
> +    Vector3 MovePoint = Vector3.zero;
[MUST]
先頭が大文字になっているので修正してください。

2021-07-26 01:04 UTC, tricore-r-hattori commented on Assets/Script/HandSwipeForceCalculation.cs
> +    public float GetSpeed { get { return speed; } }
public float Speed { get; private set; } = 0.0f;
上記のように記入し修正しました。

2021-07-26 03:48 UTC, tricore-r-hattori commented on Assets/Script/HandScroll.cs
> +            Destroy(gameObject);
同シーンによる再スタートを考慮せずに、ただ処理を軽くするために手を消去していました。
SetActive(false)と書いて修正しました。

2021-07-26 03:59 UTC, tricore-r-hattori commented on Assets/Script/PositionSynchronize.cs
> +        if (isHitPlayer)
if (isHitPlayer && Input.GetMouseButtonDown(0))に変更し修正しました。

2021-07-26 04:00 UTC, tricore-r-hattori commented on Assets/Script/TileChangeImage.cs
> +public class TileChangeImage : MonoBehaviour
スクリプト名をTileImageChangerに変え、修正しました。

2021-07-26 04:02 UTC, tricore-r-hattori commented on Assets/Script/TileScroll.cs
> +public class TileScroll : MonoBehaviour
スクリプト名をTileScrollerに変え、修正しました。

2021-07-26 04:03 UTC, tricore-r-hattori commented on Assets/Script/TileScroll.cs
> +    Vector3 MovePoint = Vector3.zero;
movePointに変え、修正しました。

2021-07-26 04:03 UTC, tricore-r-hattori commented on Assets/Script/HandScroll.cs
> +public class HandScroll : MonoBehaviour
スクリプト名をHandScrollerに変え、修正しました。

2021-07-26 04:04 UTC, tricore-r-hattori commented on Assets/Script/HandSwipeForceCalculation.cs
> +        speed = distance / (seconds * seconds);
// 加速度を計算
上記のコメントに変更し修正しました。

2021-07-26 04:06 UTC, tricore-r-hattori commented on Assets/Script/HandScroll.cs
> +        velocity = new Vector3(0, Time.deltaTime * scrollSpeedY);
起動するpcによってフレームレートが一定でないので、Time.deltaTimeを掛けました。

2021-07-26 04:12 UTC, tricore-r-hattori commented on Assets/Script/HandScroll.cs
> +        velocity = new Vector3(0, Time.deltaTime * scrollSpeedY);
// スクロール速度にスワイプ時の力を掛けて瓦の割る枚数に変化を加える
上記のコメントに変更し、修正しました。

2021-07-26 05:24 UTC, tricore-r-hattori commented on Assets/Script/PositionSynchronize.cs
> +    void SetObjectPos()
// 対象のオブジェクトと当たったらかつマウスの左ボタンが押されている時にマウスの座標と同期する
 if (isHitPlayer && Input.GetMouseButton(0))
{
         // アタッチされているオブジェクトの座標をマウスの座標に設定
         SetObjectPos();
 }

上記のようにSetObjectPos関数をif文の中に書き、修正しました。

2021-07-26 06:24 UTC, tricore-r-hattori commented on Assets/Script/TileChangeImage.cs
> +    const float BreakTileSpriteChangePointY = -1.0f;
空のオブジェクトのポジションと対象のオブジェクトのポジションを比較して、処理を実行するように変更し、修正しました。

2021-07-26 06:27 UTC, tricore-r-hattori commented on Assets/Script/HandScroll.cs
> +    const float ScrollEndPointY = 500.0f;
空のオブジェクトを用意し、そのオブジェクトの座標を動かすことによって、スクロール終了地点を調整できるようにしました。
また、空のオブジェクトのポジションと対象のオブジェクトのポジションを比較して、処理を実行するように変更し、修正しました。

2021-07-26 07:18 UTC, tricore-r-hattori commented
下記のScriptを追加しました。
〇Script
・BaseScroller
・HitCheck

申し訳ないのですが、追加で確認よろしくお願いします。

2021-07-26 07:20 UTC, tricore-r-hattori commented on Assets/Script/TileScroll.cs
> +        velocity = new Vector3(0, Time.deltaTime * scrollSpeedY);
BaseScrollerという親クラスを用意し、共通の機能を一つにまとめて修正しました。

2021-07-26 07:31 UTC, tricore-as03 approved these changes
LGTM

2021-07-26 07:37 UTC, tricore-as07 commented on Assets/Script/HandScroll.cs
> +        velocity = new Vector3(0, Time.deltaTime * scrollSpeedY);
Time.deltaTimeをかけてフレームレートの変動に対応するのであれば、
Updateなどの毎フレーム処理を行う箇所でTime.deltaTimeをかけないと意味がないので気を付けてください。

2021-07-26 07:40 UTC, tricore-as07 commented on Assets/Script/HandSwipeForceCalculation.cs
> +        speed = distance / (seconds * seconds);
こちらの計算結果が加速度であれば、speedという変数名も合わなくなります。
また、値の使用方法が加速度の意味と異なっているのでそちらも修正が必要です。

2021-07-26 08:53 UTC, tricore-as07 approved these changes
LGTM

2021-07-26 08:59 UTC, tricore-t-yui requested changes
・HandSwipeForceCalculationという名前なら計算だけをもつstatic classのような印象をうける。にもかかわらずMonobehaviourである上に計算を始めるための指の当たり判定等も一緒に入ってしまっている。分離するか、HandSwipeController等の名前であるべきでは

2021-07-26 08:59 UTC, tricore-t-yui commented on Assets/Script/BaseScroller.cs
> +        isProcessOnce = true;
[Q]
初期化なのに速度は初期化しないのか

2021-07-26 08:59 UTC, tricore-t-yui commented on Assets/Script/HandSwipeForceCalculation.cs
>          // 瓦の座標を設定
[Q]
何かが当たったらなんでもこの処理にはいるけど問題ないのか

2021-07-26 08:59 UTC, tricore-t-yui commented on Assets/Script/HitCheck.cs
> +        // オブジェクトと当たった
[Q]
当たったら何でも作業開始になるが問題ないのか

2021-07-26 08:59 UTC, tricore-t-yui commented on Assets/Script/HitCheck.cs
> +        // 瓦のスクロールが止まったら、それぞれの処理を止めるためにフラグを切り替える
[MUST]
isHitは「Hitしているか」のフラグであってスクロールは関係ない
スクロール状況で変わるならこのフラグは別の役割をもつ別の名前のフラグとなるはず

2021-07-26 08:59 UTC, tricore-t-yui commented on Assets/Script/PositionSynchronize.cs
> +            if (Input.GetMouseButtonDown(0))
[MUST]
GetMouseButtonDown等のデバッグ用関数を使っていて後々変更予定ならコメントを入れる

2021-07-26 08:59 UTC, tricore-t-yui commented on Assets/Script/PositionSynchronize.cs
> +    void SetObjectPos()
[MUST]
そもそも「アタッチされているオブジェクトの座標をマウスの座標に設定する処理」＝SetObjectPosという名前に結びつかないのでふさわしい名前に改名してください

2021-07-28 01:10 UTC, tricore-r-hattori commented on Assets/Script/HitCheck.cs
> +        // 瓦のスクロールが止まったら、それぞれの処理を止めるためにフラグを切り替える
このフラグはスクロールを開始させるためのオブジェクトと当たったか確認するためのふらぐなので、
isScrollStartObjectHitという名前に変更しました。

2021-07-28 01:24 UTC, tricore-r-hattori commented on Assets/Script/BaseScroller.cs
> +        isProcessOnce = true;
初期化忘れです。また、スクロールがストップしたかのフラグを初期化していませんでした。
velocity = Vector3.zero;
isScrollStop = false;
上記のように書いて修正しました。

2021-07-28 02:14 UTC, tricore-r-hattori commented on Assets/Script/PositionSynchronize.cs
> +            if (Input.GetMouseButtonDown(0))
// TODO: 後に、タッチした時の条件に変更
上記のTODOコメントを追加して修正しました。

2021-07-28 02:21 UTC, tricore-r-hattori commented on Assets/Script/HandSwipeForceCalculation.cs
>          // 瓦の座標を設定
if (collision.tag == "ScrollStartPoint") {}
スクロールを開始せるためのオブジェクトと当たった時に処理を行うように上記の条件を増やしました。

2021-07-28 02:21 UTC, tricore-r-hattori commented on Assets/Script/HitCheck.cs
> +        // オブジェクトと当たった
if (collision.tag == "Hand") {}
手と当たった時に処理を行うように上記の条件を増やしました。

2021-07-28 02:48 UTC, tricore-t-yui requested changes

2021-07-28 02:48 UTC, tricore-t-yui commented on Assets/Script/BaseScroller.cs
> +    public bool isScrollStop { get; private set; } = false;
[MUST]
プロパティはパスカルケース

2021-07-28 02:48 UTC, tricore-t-yui commented on Assets/Script/ScrollStartObjectHitCheck.cs
> +    public bool isScrollStartObjectHit { get; private set; } = false;
[MUST]
プロパティはパスカルケース

2021-07-28 02:48 UTC, tricore-t-yui commented on Assets/Script/ScrollStartObjectHitCheck.cs
> +            isScrollStartObjectHit = false;
[MUST]
「スクロールを開始せるためのオブジェクトと当たったかのフラグ」なのにスクロールが停止したときにフラグをおろしている

2021-07-28 03:08 UTC, tricore-r-hattori commented on Assets/Script/BaseScroller.cs
> +    public bool isScrollStop { get; private set; } = false;
IsScrollStop
上記のプロパティ名をパスカルケースに戻し修正しました。

2021-07-28 03:08 UTC, tricore-r-hattori commented on Assets/Script/ScrollStartObjectHitCheck.cs
> +    public bool isScrollStartObjectHit { get; private set; } = false;
IsScrollStartObjectHit
上記のプロパティ名をパスカルケースに戻し修正しました。

2021-07-28 03:49 UTC, tricore-r-hattori commented on Assets/Script/ScrollStartObjectHitCheck.cs
> +            isScrollStartObjectHit = false;
IsScrollControllObjectHit
上記のフラグを切り替えることによってスクロールの開始と終了を操作できるように修正しました。

2021-07-28 05:15 UTC, tricore-t-yui commented on Assets/Script/ScrollStartObjectHitCheck.cs
> +            isScrollStartObjectHit = false;
意図が伝わっていないようです

2021-07-28 05:15 UTC, tricore-t-yui requested changes
修正されていないものがあるのでコメント

2021-07-28 06:42 UTC, tricore-r-hattori commented on Assets/Script/ScrollStartObjectHitCheck.cs
> +            isScrollStartObjectHit = false;
スクロール処理をstateで管理する設計に変更し、修正しました。

2021-07-28 06:46 UTC, tricore-t-yui approved these changes
nitsあるが一応approve

2021-07-28 06:46 UTC, tricore-t-yui commented on Assets/Script/ScrollControllObjectHitCheck.cs
> +    CannotScrolling,
[nits]
Scrollableがスクロール可能なら、対義語はUnScrollableです

2021-07-28 06:52 UTC, tricore-r-hattori commented on Assets/Script/ScrollControllObjectHitCheck.cs
> +    CannotScrolling,
CannotScrollingという名前をUnScrollableに変更し、修正しました

2021-07-28 06:53 UTC, merged