低確率でレア瓦が出現する処理を実装
tricore-r-hattori/BreakingTiles pull request #5
Opened 2021-07-28 09:07 UTC by tricore-r-hattori

確認点
〇Script
・RareTileChangeCheckWithProbability
・TileImageChanger
〇Prefab
・Canvas

確認方法
・GameSceneが起動シーン
　→Unityで何度も実行を繰り返してください。
　　→低確率でレアな瓦が出現します。

2021-07-28 09:27 UTC, tricore-as05 requested changes

2021-07-28 09:27 UTC, tricore-as05 commented on Assets/Script/RareTileChangeCheckWithProbability.cs
> +    // 確率
[MUST]
ここだけsummaryになってない

2021-07-28 09:27 UTC, tricore-as05 commented on Assets/Script/RareTileChangeCheckWithProbability.cs
> +    bool Probability_(float _percent)
[MUST]
謎の_がついているので削除してください
あとProbabilityだけだと確率って意味だけなので、
「当選してレアな瓦を生成することになったかどうか」というのが関数名では伝わらない気がします

2021-07-28 09:27 UTC, tricore-as05 commented on Assets/Script/RareTileChangeCheckWithProbability.cs
> +    void Start()
[Q]
瓦生成って同じStartでやってますけど、指定間に合ってますか？
こういった場合は、Startよりも早いタイミングで呼ばれるAwakeを使った方が安全かもしれません

2021-07-28 09:27 UTC, tricore-as05 commented on Assets/Script/RareTileChangeCheckWithProbability.cs
> +public class RareTileChangeCheckWithProbability : MonoBehaviour
[nits]
WithProbabilityが冗長な気がするので、
RareTileChangeCheckerとかでいい気がします

2021-07-28 09:27 UTC, tricore-as05 commented on Assets/Script/TileImageChanger.cs
> +    Sprite rareTileSprite = default;
[MUST]
Spriteの参照が増えているので、
割れている瓦と、割れていない瓦でListにまとめましょう
番号の指定はenumなどを使うと良いかと

2021-07-28 09:27 UTC, tricore-as05 commented on Assets/Script/TileImageChanger.cs
> +        // 画像を変える地点より低い位置にいた時かつ割れている瓦の状態かつレア瓦に変更できない時に画像を変換
[Q]
「&& tileImage.sprite == breakTileSprite」のようなスプライトを比較する条件式はいらないのでは？
位置の判定のみで問題ないかと思います。

[MUST]
こっから下の4つの条件式ですが、まとめられる条件があるのでまとめましょう

2021-07-29 03:03 UTC, tricore-r-hattori commented on Assets/Script/TileImageChanger.cs
> +    Sprite rareTileSprite = default;
割れている瓦と、割れていない瓦でList化しました。

2021-07-29 03:03 UTC, tricore-r-hattori commented on Assets/Script/RareTileChangeCheckWithProbability.cs
> +public class RareTileChangeCheckWithProbability : MonoBehaviour
RareTileChangeCheckerという関数名に修正しました。

2021-07-29 03:03 UTC, tricore-r-hattori commented on Assets/Script/RareTileChangeCheckWithProbability.cs
> +    void Start()
Startで実行したところ、たまにIsRareTileChangeフラグが切り替わらないことを確認しました。
なので、Awakeに修正しました。

2021-07-29 03:03 UTC, tricore-r-hattori commented on Assets/Script/RareTileChangeCheckWithProbability.cs
> +    bool Probability_(float _percent)
CreateRareTileProbabilityという関数名に修正しました。

2021-07-29 03:03 UTC, tricore-r-hattori commented on Assets/Script/RareTileChangeCheckWithProbability.cs
> +    // 確率
申し訳ないのですが、複数質問失礼します。
[SerializeField]の部分でしょうか？
もしそうでしたら、ここ以外の[SerializeField]もsummaryにしていないので、変更したほうがよろしいでしょうか？

2021-07-29 03:19 UTC, tricore-r-hattori commented on Assets/Script/TileImageChanger.cs
> +        // 画像を変える地点より低い位置にいた時かつ割れている瓦の状態かつレア瓦に変更できない時に画像を変換
「&& tileImage.sprite == breakTileSprite」という条件式を追加した理由は、画像を変える地点から上か下の位置にいた場合に常に毎フレーム画像を変えてしまう無駄な処理が発生しました(変える前の画像と変えた後の画像は同じなので実質画像は変わっていない)。なので、無駄な処理をしないためにこのような条件式を追加しました。

4つの条件式に関しては、条件をまとめて修正しました。
まだまとめれるのなら指摘をお願いします。

2021-07-29 03:24 UTC, tricore-as05 commented on Assets/Script/RareTileChangeCheckWithProbability.cs
> +    // 確率
はい、[SerializeField]の部分です。
必ずしもsummaryにしろというわけではなく、summaryとそれ以外が混在しているので、
やるならどちらかに統一してほしいということになります。

2021-07-29 03:25 UTC, tricore-as05 commented on Assets/Script/RareTileChangeCheckWithProbability.cs
> +    bool Probability_(float _percent)
CreateRareTileProbabilityなら「確率でレアな瓦を作る」という意味になります。
この関数はでやっていることは「確率でレアな瓦を作るかどうかのフラグ」なので、
命名するとするとIsCreateRareTileProbabilityとなるのではないでしょうか？

2021-07-29 03:26 UTC, tricore-as07 commented on Assets/Script/RareTileChangeChecker.cs
> +    float percent = 100.0f;
[nits]
％を設定してほしい場合、上限加減がある思うので下記のリンクのRangeAttributeを使うとunity側で設定できる値を制限できます。
https://docs.unity3d.com/ja/current/ScriptReference/RangeAttribute.html

2021-07-29 03:31 UTC, tricore-as07 commented on Assets/Script/RareTileChangeChecker.cs
> +        if (_percent == OneHundredPercent && probabilityRate == _percent)
[Q]
確率が100%という条件だけで当選な気がするのですが、
「probabilityRate == _percent」には何の意味があるのでしょうか？

2021-07-29 03:37 UTC, tricore-as05 commented on Assets/Script/TileImageChanger.cs
> +                tileImage.sprite = breakTileSprite[(int)BreakTileType.BreakRareTile];
[Q]
これ結果的なIntはあってるけどenumの指定間違ってません？
瓦のタイプで判断するならBreakTileTypeではなく、TileTypeでは？

2021-07-29 03:37 UTC, tricore-as05 commented on Assets/Script/TileImageChanger.cs
> +                tileImage.sprite = breakTileSprite[(int)BreakTileType.BreakTile];
[Q]
> これ結果的なIntはあってるけどenumの指定間違ってません？
> 瓦のタイプで判断するならBreakTileTypeではなく、TileTypeでは？

ここも

2021-07-29 03:37 UTC, tricore-as05 commented on Assets/Script/TileImageChanger.cs
> +public enum BreakTileType
[Q]
瓦の割れている画像と、割れていない画像はリストで分けられているのでBreakTileTypeはいらないのでは？

2021-07-29 03:37 UTC, tricore-as05 commented on Assets/Script/TileImageChanger.cs
> +        // 画像を変える地点より低い位置にいた時かつ割れている瓦の状態かつレア瓦に変更できない時に画像を変換
[MUST]
先ほど直接説明した通り、
そもそも「&& tileImage.sprite == breakTileSprite」のspriteの比較は問答無用でアウトと覚えてもらって構わないので、
こういった比較をする場合はフラグなどで対応してください

2021-07-29 03:41 UTC, tricore-as05 requested changes

2021-07-29 03:41 UTC, tricore-as05 commented on Assets/Script/TileImageChanger.cs
> +            if (tileTransform.position.y > tileSpriteChangePoint.position.y && tileImage.sprite == tileSprite[(int)TileType.RareTile])
[MUST]
返信にも記載しましたが、
スプライトを比較する条件式の修正をお願いします。

2021-07-29 03:45 UTC, tricore-r-hattori commented on Assets/Script/RareTileChangeCheckWithProbability.cs
> +    // 確率
summaryでコメントを統一して修正しました。

2021-07-29 03:46 UTC, tricore-r-hattori commented on Assets/Script/RareTileChangeCheckWithProbability.cs
> +    bool Probability_(float _percent)
IsCreateRareTileProbabilityという関数名に修正しました。

2021-07-29 04:02 UTC, tricore-r-hattori commented on Assets/Script/TileImageChanger.cs
> +        // 画像を変える地点より低い位置にいた時かつ割れている瓦の状態かつレア瓦に変更できない時に画像を変換
isBreakTileというbool型の変数を用意し、フラグで管理できるように修正しました。

2021-07-29 04:03 UTC, tricore-r-hattori commented on Assets/Script/RareTileChangeChecker.cs
> +    float percent = 100.0f;
RangeAttributeを使用し0～100の範囲で値を設定できるように修正しました。

2021-07-29 05:22 UTC, tricore-r-hattori commented on Assets/Script/RareTileChangeChecker.cs
> +        if (_percent == OneHundredPercent && probabilityRate == _percent)
乱数の値と確率の値が一緒だった時の条件を加えたのですが、&&にしているのが間違いでした。
「&& probabilityRate == _percent」の条件式を消して、その下のelse ifの条件式を「probabilityRate <= _percent」に変更し、修正しました。

2021-07-29 05:26 UTC, tricore-r-hattori commented on Assets/Script/TileImageChanger.cs
> +            if (tileTransform.position.y > tileSpriteChangePoint.position.y && tileImage.sprite == tileSprite[(int)TileType.RareTile])
isBreakTileというbool型の変数を用意し、フラグで管理できるように修正しました。

2021-07-29 05:36 UTC, tricore-r-hattori commented on Assets/Script/TileImageChanger.cs
> +public enum BreakTileType
確かにいらないです。
BreakTileTypeを消して修正しました。

2021-07-29 05:37 UTC, tricore-r-hattori commented on Assets/Script/TileImageChanger.cs
> +                tileImage.sprite = breakTileSprite[(int)BreakTileType.BreakTile];
配列の要素をTileTypeで指定し、修正しました。

2021-07-29 05:37 UTC, tricore-r-hattori commented on Assets/Script/TileImageChanger.cs
> +                tileImage.sprite = breakTileSprite[(int)BreakTileType.BreakRareTile];
BreakTileTypeを消して修正しました。

2021-07-29 05:48 UTC, tricore-as07 approved these changes
LGTM

2021-07-29 06:11 UTC, tricore-as05 commented on Assets/Script/TileImageChanger.cs
[MUST]
enumのコメントがないです

2021-07-29 06:11 UTC, tricore-as05 commented on Assets/Script/RareTileChangeCheckWithProbability.cs
> +    // 確率
[MUST]
RareTileChangeChecker.csの変数のコメントがsummaryで、TileImageChanger.csはsummaryを使っていないです。
全てのスクリプトで変数コメントにsummaryを使うかどうかを統一してください

2021-07-29 06:22 UTC, tricore-r-hattori commented on Assets/Script/TileImageChanger.cs
「タイルの種類」とコメントを書いて修正しました。

2021-07-29 06:49 UTC, tricore-r-hattori commented on Assets/Script/RareTileChangeCheckWithProbability.cs
> +    // 確率
[SerializeField]のコメントはsummaryを使わない方で統一します。

2021-07-29 06:54 UTC, tricore-as05 approved these changes
LGTM

2021-07-29 07:12 UTC, tricore-t-yui approved these changes
nits数件だがApprove

2021-07-29 07:12 UTC, tricore-t-yui commented on Assets/Script/TileImageChanger.cs
> +    List<Sprite> tileSprite = default;
[nits]
リストならリストとわかるようにtileSpriteListという変数名のほうが親切かな

2021-07-29 07:12 UTC, tricore-t-yui commented on Assets/Script/TileImageChanger.cs
> +            if (tileTransform.position.y > tileSpriteChangePoint.position.y && !isBreakTile)
[Q]
elseifじゃなくていいのかな

2021-07-29 07:53 UTC, tricore-r-hattori commented on Assets/Script/TileImageChanger.cs
> +    List<Sprite> tileSprite = default;
tileSpriteListという変数名に修正しました。

2021-07-29 07:54 UTC, tricore-r-hattori commented on Assets/Script/TileImageChanger.cs
> +            if (tileTransform.position.y > tileSpriteChangePoint.position.y && !isBreakTile)
else ifにしてしまうと処理に入らず画像を切り替えれなくなってしまいます。
なのでifのままでいきます。

2021-07-29 08:00 UTC, merged