シーケンス処理実装
tricore-r-hattori/BreakingTiles pull request #8
Opened 2021-08-02 00:50 UTC by tricore-r-hattori

アニメーションステートでシーケンスを実装しました。

確認点
〇Animator
・GameSequenceAnimator
〇Animation
・GamePlayFadeOutAnimtion
・ResulFadeOutAnimtion
・TitlelFadeOutAnimtion
・TutorialFadeOutAnimtion
・GamePlayFadeInAnimation
・ResultFadeInAnimation
・TitleFadeInAnimation
・TutorialFadeInAnimation
〇prefab
・Canvas
〇Script
・GiveUpButtonDraw
・TitleTransition
・ResultTransition

確認方法
・GameSceneが起動シーン
・タイトルでスタートボタンを押すとTitleObjectが非アクティブ化し、GamePlayObjectがアクティブ化してゲーム中に遷移します。
・タイトルでチュートリアルボタンを押すとTitleObjectが非アクティブ化し、TutorialObjectがアクティブ化してチュートリアルに遷移します。
・チュートリアルで画面をクリックするとTutorialObjectが非アクティブ化し、TitleObjectがアクティブ化してタイトルに遷移します。
・ゲーム中にギブアップボタンを押すとGamePlayObjectが非アクティブ化し、TitleObjectがアクティブ化してタイトルに遷移します。
・ゲーム中に瓦のスクロールが止まったらGamePlayObjectが非アクティブ化し、ResultObjectがアクティブ化してリザルトに遷移します。
・リザルトで画面をクリックするとResultObjectが非アクティブ化し、TitleObjectがアクティブ化してタイトルに遷移します。

2021-08-02 01:26 UTC, tricore-as05 requested changes

2021-08-02 01:26 UTC, tricore-as05 commented on Assets/Script/GiveUpButtonDraw.cs
> +public class GiveUpButtonDraw : MonoBehaviour
[MUST]
GiveUpButtonDrawerにしてください

[IMO]
間接的に呼ぶならまだしも、もしギブアップボタンそのものにこのクラスがついているのだとしたら、
GiveUpButtonって名前にして、ギブアップボタン描画クラスじゃなくて、ギブアップボタンクラスって扱いでいいのではないかと思いました。
ボタン関数とか登録あるだろうし...

2021-08-02 01:26 UTC, tricore-as05 commented on Assets/Script/ResultTransition.cs
> +            if (waitSequenceFrameCount > waitSequenceFrame)
[Q]
なぜ何秒か待たないといけないのか教えてください

[MUST]
秒数待ちの為だけにUpdateを使っているならコルーチンに変えてください

2021-08-02 01:26 UTC, tricore-as05 commented on Assets/Script/TitleTransition.cs
> +    void Update()
[Q]
TitleTransition.csとResutTransition.cs分けた理由ってありますか？
この規模だったらまとめてシーン遷移クラス作った方がいいかとおもうのですが

[MUST]
このクラスのままで行くなら、せめてタイトルに遷移したら非アクティブにしてください。
余計なUpdateが回っています。

2021-08-02 01:26 UTC, tricore-as05 commented on Assets/Script/Tile/TileImageChanger.cs
> +using System;
[Q]
結局処理追加してないならこのusingいらないのでは？

2021-08-02 01:26 UTC, tricore-as05 commented on Assets/Script/Scroll/HandScroller.cs
> +        isProcessOnce = true;
[Q]
Awakeで処理行えば一回だけ処理行うので、OnEnableにある処理をAwakeに移動させればいいのではないでしょうか？

2021-08-02 01:26 UTC, tricore-as05 commented on Assets/Script/Scroll/TileScroller.cs
> +        isProcessOnce = true;
[Q]
> Awakeで処理行えば一回だけ処理行うので、OnEnableにある処理をAwakeに移動させればいいのではないでしょうか？

ここも

2021-08-02 01:26 UTC, tricore-as05 commented on Assets/Script/Scroll/HandScroller.cs
> +                //gameObject.SetActive(false);
[Q]
これコメント化のまんまだけど大丈夫ですか？
問題ないなら消してください

2021-08-02 02:05 UTC, tricore-r-hattori commented on Assets/Script/GiveUpButtonDraw.cs
> +public class GiveUpButtonDraw : MonoBehaviour
Drawerは"引き出し"という意味になるので、このクラスの名前だと他人がこの処理を見た時に勘違いするかもしれません。
そして、GiveUpButtonDrawクラスはGiveUpButtonManagerというギブアップボタンを管理するオブジェクトにアタッチされています。

複数質問失礼します。
ボタン関数と登録というのは具体的にどういった処理なのでしょうか？
修正を行った方がよろしいでしょうか？

2021-08-02 02:53 UTC, tricore-as05 requested changes

2021-08-02 02:53 UTC, tricore-as05 commented on Assets/Script/TitleTransition.cs
> +            sequenceAnimator.SetTrigger("isTitleScene");
[MUST]
"isTitleScene"の直指定はやめてstringの変数を作ってください

2021-08-02 03:04 UTC, tricore-as05 commented on Assets/Script/GiveUpButtonDraw.cs
> +public class GiveUpButtonDraw : MonoBehaviour
Drawerでも伝わるとは思いますが、いやだったらRendererとかでもいいかもしれません。

そもそもGiveUpButtonManagerと描画処理をわけてGiveUpButtonDrawを作った意図ってなんでしょうか？
一緒にしてていい気がしますが....

2021-08-02 06:27 UTC, tricore-r-hattori commented on Assets/Script/Tile/TileImageChanger.cs
> +using System;
消し忘れです。修正しました。

2021-08-02 06:27 UTC, tricore-r-hattori commented on Assets/Script/Scroll/HandScroller.cs
> +                //gameObject.SetActive(false);
消し忘れです。修正しました。

2021-08-02 06:45 UTC, tricore-r-hattori commented on Assets/Script/TitleTransition.cs
> +            sequenceAnimator.SetTrigger("isTitleScene");
stringの変数を用意して修正しました。

2021-08-02 07:23 UTC, tricore-r-hattori commented on Assets/Script/Scroll/HandScroller.cs
> +        isProcessOnce = true;
Awakeで処理を行った際に、オブジェクトが非アクティブなので手のポジションを取得することが出来ませんでした。
ですので、アクティブになった際に一回だけ手の初期値を設定するような処理にしました。

2021-08-02 07:23 UTC, tricore-r-hattori commented on Assets/Script/Scroll/TileScroller.cs
> +        isProcessOnce = true;
Awakeで処理を行った際に、オブジェクトが非アクティブなので手のポジションを取得することが出来ませんでした。
ですので、アクティブになった際に一回だけ手の初期値を設定するような処理にしました。

2021-08-02 07:29 UTC, tricore-r-hattori commented on Assets/Script/ResultTransition.cs
> +            if (waitSequenceFrameCount > waitSequenceFrame)
> なぜ何秒か待たないといけないのか教えてください
スクロールが終わった際に瞬時に遷移してしまっていたので、余韻を残すために数秒待つ処理を実装しました。

> 秒数待ちの為だけにUpdateを使っているならコルーチンに変えてください
コルーチンに変えて、修正しました。

2021-08-02 07:30 UTC, tricore-r-hattori commented on Assets/Script/ResultTransition.cs
> +            if (waitSequenceFrameCount > waitSequenceFrame)
> なぜ何秒か待たないといけないのか教えてください

スクロールが終わった際に瞬時に遷移してしまっていたので、余韻を残すために数秒待つ処理を実装しました。

> 秒数待ちの為だけにUpdateを使っているならコルーチンに変えてください

コルーチンに変えて、修正しました。

2021-08-02 07:38 UTC, tricore-r-hattori commented on Assets/Script/TitleTransition.cs
> +    void Update()
> TitleTransition.csとResutTransition.cs分けた理由ってありますか？

ResutTransitionの方でコルーチンを追加し、TitleTransitionの方ではコルーチンを行っていないので、別々のままでいきます。

> このクラスのままで行くなら、せめてタイトルに遷移したら非アクティブにしてください。
余計なUpdateが回っています。

タイトルに遷移した際にAnimationで非アクティブ化しています。

2021-08-02 07:47 UTC, tricore-r-hattori commented on Assets/Script/GiveUpButtonDraw.cs
> +public class GiveUpButtonDraw : MonoBehaviour
GiveUpButtonRendererというクラス名に修正しました。

GiveUpButtonManagerという空のオブジェクトにGiveUpButtonRenderer(元GiveUpButtonDraw)クラスをアタッチしているので、分けてはいないと思います...
補足※GiveUpButtonManagerオブジェクトでGiveUpButtonオブジェクトの描画のON/OFFを行っています。

2021-08-02 08:01 UTC, tricore-as03 requested changes

2021-08-02 08:01 UTC, tricore-as03 commented on Assets/Script/ResultTransition.cs
> +        resultTriggerString = "isResultScene";
[Q]
なぜわざわざOnEnableで文字列を渡しているのでしょうか。

[MUST]
```
string CoroutineString = "WaitResultSequenceCoroutine";
```
文字列が変わらないのであればconst stringにして、定数宣言時にそのまま文字列を渡してしまって問題ないと思います。

2021-08-02 08:01 UTC, tricore-as03 commented on Assets/Script/ResultTransition.cs
> +        yield return new WaitForSeconds(1.0f);
[MUST]
こちらも値を直接指定するのではなく、変数化してください。

2021-08-02 08:27 UTC, tricore-as03 approved these changes
LGTM

2021-08-02 09:16 UTC, tricore-r-hattori commented on Assets/Script/Scroll/HandScroller.cs
> +        isProcessOnce = true;
OnEnableにある処理の一部をAwakeに移動し修正しました。

2021-08-02 09:16 UTC, tricore-r-hattori commented on Assets/Script/Scroll/TileScroller.cs
> +        isProcessOnce = true;
OnEnableにある処理の一部をAwakeに移動し修正しました。

2021-08-02 09:19 UTC, tricore-r-hattori commented on Assets/Script/GiveUpButtonDraw.cs
> +public class GiveUpButtonDraw : MonoBehaviour
GiveUpButtonManagerのオブジェクト名をGiveUpButtonActivatorに修正しました。
GiveUpButtonRendererのクラス名をGiveUpButtonに修正しました。

2021-08-03 00:48 UTC, tricore-r-hattori commented on Assets/Script/TitleTransition.cs
> +    void Update()
TitleTransition.csとResutTransition.csをSequence.csのスクリプトにまとめました

2021-08-03 00:49 UTC, tricore-as05 commented on Assets/Script/GiveUpButtonDraw.cs
> +public class GiveUpButtonDraw : MonoBehaviour
[nits]
GiveUpButtonManagerのオブジェクト名は単純に親オブジェクトなんで、GiveUpButtonRootとかでいい気がします。
GiveUpButtonActivatorってオブジェクトがGiveUpButtonというクラスを持つのってなんか違和感があります

2021-08-03 01:03 UTC, tricore-as05 requested changes

2021-08-03 01:03 UTC, tr-k-oishi commented on Assets/Script/Sequence.cs
> +public class Sequence : MonoBehaviour
[MUST]
SequenceControllerとかにしてください

2021-08-03 01:03 UTC, tr-k-oishi commented on Assets/Script/Scroll/ScrollControllObjectHitCheck.cs
> +    /// スクロールが止まって非アクティブになった時に呼ばれるAction
[MUST]
どういったアクションなのかまで説明してください
例：スクロールが止まって非アクティブになった時に呼ばれるシーン遷移Action

2021-08-03 01:03 UTC, tricore-as05 commented on Assets/Script/Sequence.cs
> +    const string resultCoroutineString = "WaitResultSequence";
[MUST]
コルーチンの指定にStringを渡すのはダメなので、関数そのものを渡してください。

例えばWaitResultSequenceを動かしたい場合、
StartCoroutine(WaitResultSequence());で動きます。

2021-08-03 01:21 UTC, tricore-r-hattori commented on Assets/Script/Sequence.cs
> +public class Sequence : MonoBehaviour
クラス名をSequenceControllerに修正しました。

2021-08-03 01:21 UTC, tricore-r-hattori commented on Assets/Script/Scroll/ScrollControllObjectHitCheck.cs
> +    /// スクロールが止まって非アクティブになった時に呼ばれるAction
onScrollStopResultSequenceという変数名に変更し、コメントを修正しました。

2021-08-03 01:21 UTC, tricore-r-hattori commented on Assets/Script/Sequence.cs
> +    const string resultCoroutineString = "WaitResultSequence";
string定数を削除して、関数そのものを指定する形に修正しました。

2021-08-03 01:36 UTC, tricore-as05 approved these changes
LGTM

2021-08-03 03:49 UTC, tricore-t-yui approved these changes
ひとまず一旦Approve

2021-08-03 03:49 UTC, tricore-t-yui commented on Assets/Script/GiveUpButtonActivator.cs
> +        if (gameObject.activeInHierarchy)
[Q]
OnEnableでやっているのだから不要では？

2021-08-03 03:49 UTC, tricore-t-yui commented on Assets/Script/Scroll/ScrollControllObjectHitCheck.cs
> +        if (_collision.tag == "Hand")
[nits]
本来MUST。tag名の直値指定はまずい

2021-08-03 03:49 UTC, tricore-t-yui commented on Assets/Script/SequenceController.cs
> +            StartCoroutine(WaitTitleSequence());
[nits]
本来はmust
コルーチンの連続実行を考慮しておらず、エラー処理がない

2021-08-03 04:07 UTC, tricore-r-hattori commented on Assets/Script/Scroll/ScrollControllObjectHitCheck.cs
> +        if (_collision.tag == "Hand")
const string型のhandTagを用意して、その定数で指定しました。

2021-08-03 04:07 UTC, tricore-r-hattori commented on Assets/Script/GiveUpButtonActivator.cs
> +        if (gameObject.activeInHierarchy)
不要なので消去しました。

2021-08-03 04:56 UTC, merged