割った瓦をカウントする処理
tricore-r-hattori/BreakingTiles pull request #9
Opened 2021-08-03 05:33 UTC by tricore-r-hattori

確認点
〇Script
・BrokenTileScoreActivator
・CountBrokenTile
・TileImageChanger
〇Prefab
・Canvas

確認方法
・GameSceneが起動シーン。
　→ゲーム中に手を掴むためにマウスの左クリックを押し続けてください。
　　→手を瓦にスワイプすると瓦が割れて画面中央に割った瓦をカウントするテキストが表示されます。

2021-08-03 05:49 UTC, tricore-as05 requested changes

2021-08-03 05:49 UTC, tricore-as05 commented on Assets/Script/BrokenTileScoreActivator.cs
> +public class BrokenTileScoreActivator : MonoBehaviour
[MUST]
色々なところで確かbreakTileという命名を使っていたと思うのですが、
ここにきて急にbrokenTileという命名になると、表記ブレが起きているので統一してください

[Q]
BrokenTileScoreActivator とCountBrokenTile を分けた理由とかってありますか？

[nits]
特に理由なく分けたのであれば一緒にしてほしいです。
前も指摘したように無駄なMonoBehaviourを継承せずに済むので

2021-08-03 05:49 UTC, tricore-as05 commented on Assets/Script/CountBrokenTile.cs
> +public class CountBrokenTile : MonoBehaviour
[Q]
BrokenTileCounterでは？

2021-08-03 05:49 UTC, tricore-as05 commented on Assets/Script/BrokenTileScoreActivator.cs
> +            BrokenTileScoreText.SetActive(true);
[MUST]
わざわざUpdateで回す必要ないと思うので、
public関数とかにして、外部から呼び出した方がいい気がします。

2021-08-03 05:49 UTC, tricore-as05 commented on Assets/Script/CountBrokenTile.cs
> +    List<TileImageChanger> tileImageChanger = default;
[nits]
瓦関連のマネージャークラスとかってありましたっけ？
あればそちらを経由して関数登録をしてほくはあります。
現状だとこのクラスがほぼすべての瓦の参照をもっていることになり、すごく肥大化しているように感じます。

マネージャークラスがなければ大丈夫です

2021-08-03 05:52 UTC, tricore-as07 requested changes

2021-08-03 05:52 UTC, tricore-as07 commented on Assets/Script/BrokenTileScoreActivator.cs
> +        if (scrollControllObjectHitCheck.State == ScrollState.Scrollable)
[Q]
この条件を判定するためだけにBrokenTileScoreActivator作ったのであれば不適切かと思われます。
ScrollControllObjectHitCheckでStateをScrollState.Scrollableにしている箇所で呼ばれるActionを作成し、
そこでSetActive(true)をするように登録する方が無駄な関数の呼び出しや毎フレーム条件判定を行う必要がなくなります。

2021-08-03 06:11 UTC, tricore-as03 requested changes

2021-08-03 06:11 UTC, tr-t-mitsumaru commented on Assets/Script/BrokenTileScoreActivator.cs
> +    GameObject BrokenTileScoreText = default;
[MUST]
先頭大文字になってます。

2021-08-03 06:11 UTC, tricore-as03 commented on Assets/Script/Tile/TileImageChanger.cs
> +    event Action onCountBrokenTile = default;
[MUST]
関数を一つしか登録していないので、eventにする必要はないと思います。

2021-08-03 06:57 UTC, tricore-r-hattori commented on Assets/Script/BrokenTileScoreActivator.cs
> +public class BrokenTileScoreActivator : MonoBehaviour
> 確か色々なところで確かbreakTileという命名を使っていたと思うのですが、
ここにきて急にbrokenTileという命名になると、表記ブレが起きているので統一してください
記憶違いだったら気にしないでください

breakTileという命名に統一しました。

> BrokenTileScoreActivator とCountBrokenTile を分けた理由とかってありますか？

表示非表示する処理とカウントする処理を分けた方が他人が見て見やすくなるかなと思い分けたのですが、たしかに無駄にMonoBehaviourを継承しているので、二つの処理をCountBrokenTileにまとめました。

2021-08-03 06:57 UTC, tricore-r-hattori commented on Assets/Script/CountBrokenTile.cs
> +public class CountBrokenTile : MonoBehaviour
BreakTileCounterというクラス名に修正しました。

2021-08-03 06:57 UTC, tricore-r-hattori commented on Assets/Script/BrokenTileScoreActivator.cs
> +            BrokenTileScoreText.SetActive(true);
外部のScrollControllObjectHitCheckにActionを用意し、そのActionをScrollStateがScrollableになった箇所で呼ぶようにして修正しました。

2021-08-03 06:57 UTC, tricore-r-hattori commented on Assets/Script/CountBrokenTile.cs
> +    List<TileImageChanger> tileImageChanger = default;
マネージャークラスはありません。

2021-08-03 06:57 UTC, tricore-r-hattori commented on Assets/Script/BrokenTileScoreActivator.cs
> +        if (scrollControllObjectHitCheck.State == ScrollState.Scrollable)
外部のScrollControllObjectHitCheckにActionを用意し、そのActionをScrollStateがScrollableになった箇所で呼ぶようにして、修正しました。

2021-08-03 06:57 UTC, tricore-r-hattori commented on Assets/Script/BrokenTileScoreActivator.cs
> +    GameObject BrokenTileScoreText = default;
小文字にして修正しました。

2021-08-03 06:58 UTC, tricore-r-hattori commented on Assets/Script/Tile/TileImageChanger.cs
> +    event Action onCountBrokenTile = default;
eventを消去し、修正しました。

2021-08-03 07:05 UTC, tricore-as05 commented on Assets/Script/CountBrokenTile.cs
> +public class CountBrokenTile : MonoBehaviour
コンポーネント内の名前が変わってないです

2021-08-03 08:05 UTC, tr-k-oishi requested changes

2021-08-03 08:05 UTC, tricore-as05 commented on Assets/Script/Tile/TileImageChanger.cs
> +    ///
[MUST]
コメント

2021-08-03 08:18 UTC, tricore-r-hattori commented on Assets/Script/Tile/TileImageChanger.cs
> +    ///
瓦のカウント処理Actionというコメントで修正しました。

2021-08-03 08:20 UTC, tricore-as05 approved these changes
LGTM

2021-08-03 08:52 UTC, tricore-as07 approved these changes
LGTM

2021-08-03 09:18 UTC, tricore-as03 requested changes
LGTM

2021-08-03 09:20 UTC, tricore-as03 approved these changes
LGTM

2021-08-03 09:33 UTC, tricore-t-yui approved these changes
全体的に設計は気になるけど、コーディング規約は問題ないのでApprove

2021-08-03 09:33 UTC, tricore-t-yui commented on Assets/Script/BreakTileCounter.cs
> +    // 割った瓦を数えるテキスト
[nits]
テキストって言ってるのに型がextじゃないのが気になる

2021-08-04 00:43 UTC, tricore-r-hattori commented on Assets/Script/BreakTileCounter.cs
> +    // 割った瓦を数えるテキスト
TextMeshProUGUI型に変更し、修正しました

2021-08-04 00:43 UTC, merged